### ISSUE TITLE
Arreglar code coverage

### ISSUE THREAD

**Issue by ltessore** [ivanpatos/tp_taller2#58]
El coverage esta fallando y tirando el siguiente error:

Processing VersionTest/CMakeFiles/VersionTestRun.dir/VersionTest.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/resources/Folder.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/resources/User.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/resources/File.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/resources/Version.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/server/ServiceFactory.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/server/Services/UpdateFileService.cpp.gcno
Processing VersionTest/CMakeFiles/VersionTestRun.dir/__/__/main/code/server/Services/GetFolderService.cpp.gcno
Out of memory!
make[2]: *** [all_tests] Error 1
make[1]: *** [test/CMakeFiles/all_tests.dir/all] Error 2
make: *** [all] Error 2

**Comment by Artificiero** [comment]
Esto a mi no me pasa...que raro
